server:
  port: 8000
  servlet:
    context-path: /api/system


spring:
  application:
    name: management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/managerment
    username: root
    password: a123456
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
      timeout: 5000
      password: 123456
    # springAI
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-7a1fd5298eff41f590350ade6e642165
      chat:
        options:
          model: qwen-plus

mybatis-plus:
  configuration:
    # 驼峰配置
    map-underscore-to-camel-case: false
    # 开发环境打印 Sql 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Knife4j配置
# springdoc-openapi配置
springdoc:
  # get请求多参数时不需要添加额外的@ParameterObject和@Parameter注解
  default-flat-param-object: true
  # 启用swaggerUI
  swagger-ui:
    #自定义swagger前端请求路径，输入http://127.0.0.1:8080/api/system/swagger-ui.html会自动重定向到swagger页面
    path: /swagger-ui.html
    enabled: true
    operations-sorter: order
  api-docs:
    path: /v3/api-docs
    enabled: true
# knife4j相关配置 可以不用改
knife4j:
  enable: true
  setting:
    language: ZH_CN   # 中文:ZH_CN 英文:EN
    enable-swagger-models: true
    enable-dynamic-parameter: false
    enable-footer-custom: true
    enable-footer: true
    enable-document-manage: true

store:
  init:
    storeName: "qzh的便利店"
    managerId: 1991058483334778881
    contactName: "qzh"
    contactPhone: "13800138000"
    contactEmail: "qzh@example.com"
    address: "北京市朝阳区建国路88号"
    longitude: 116.481028
    latitude: 39.921983

baidu:
  weather:
    base-url: https://api.map.baidu.com/weather/v1/
    ak: jwE991y5wmyqLVa90OssRsYoqw9WfvRF
    connect-timeout-ms: 5000
    read-timeout-ms: 5000

alipay:
  appId: 9021000159653876
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCOl3o7t25rLYWOEm4rtTLuI5H6tLk1eWS3fAFmZyLB6OxhdgKLnAwiWiAYIhxw+KtGXmWj3ol8MA8HH6FAXEnBoBewb4V+cYazQxh5cG9FsvtF0X/B1kpXQfQXzSjiDDU4gvc3bkNivbaF5lftqqYlXbZJhsXrPOeVVQdYPKlm3oLtji7CVxBCw/VWcuBMD4gwEF3W41H1vsSdFQgRHZljpffEF8Rc42HQqZ0k02sfPcseIkLPqC9YD5jzIwGMgW/CZVmwcxRF9DuMMVTP3RpZRz/wMufSoD88gmx+RY6XOMsmgwzqmkIAg2Je+XTvxC1JnW/jxUJfFg9xFUJb5o9rAgMBAAECggEAV3FxVjmxDy0FYBDRWyBtsThDB1nY0oA1UYhMW34YBI5Ql5wFB5SUpGRcljAk/OqiLi8paYrJCU13icjN3Gg8Gu+QV3SsitQX5MrasW5P7pBKI5DMJhTB1izuAcKgta8C3DsEXAvUazMoQYj2lxs1dGi5pvFtYkshQaS5MlVRFXGmogIp9C7J1lZsux8008ceozZd5ymVZzrK7l76pm/9TceG5QfoOyTt2wCPOpA3ty0X7vJYJPf7jDuJYshx2lzEPJyucXRI+2a9/aYi6ZH2ixTB6670BZAczGQD1QHsRJRkovHn/iMpAtWLiih5bx+sgYgJ715mHtEpOOOggZzPoQKBgQDauoHqH5e2QoXaufbmstSleoOUUcthciHfDUWBm8oFxDCgaI5WMkwRMbGwmGV2wHItkBF9Ytmg/WJwnHIlzTMKh65kO/0cCd6UY8lDOWiaXzgKBxjBVKxk6IOsXG3WuwPEvfhjPu7FlJXGNk+gnka4n+qonMaW7wm5yRXjRs8QmQKBgQCm47BGyVfoJBb/6YU2IV1RWXmrvOvU8NCEH2xnz5GlJCKEfXG6EwQAei/ZUUiZwhgyu+0HrLuYrz833bR8Lum2IQnso2n3XtOxF5bvBwC8R2R+vUkVomY9B8uJTsN+FVotqbaiLfMCzDjvqwbHfgHsWv2GPvrDDIgpg3sTYF+uowKBgQDKfQUOOEcb3MPMNIKlGgMQWrX7FinhQWan9sJU9WN2KSUXKxQyKggPluC36q1r3UcWdRwr5towVsLOG5b09d19rxQ8COkODvj2iNZmnHwBBYt8hQte10Nte2+CnmK0+pbHiVKsljM3yJFLWTYoLL6t5qW3iMO0MQDg9I6FxCSnaQKBgFGUU4MGwTX1Dlkiqb+AJ8GwX02YGCALZ6JuSeulB6kWNNlXCNTQntAs6l7s4PRocLO8MW3i/gDxCZIhiix6MjyZgeRvLUmCzTBwO5O0dKOUsodRt/wfWqLSwKfqHJ3xihdwMpqso3Hmqp5dl/7EleQXxn5tIt9drOG+J9ec8KjJAoGAIDrctSb2wMzK2amOt59nknm4UeLKc05un8fqX4elXKiSkpeT9t9dqFSGAsOaNwZOzC6Gm9MkE6DD0F/EaFYvAvWmBIIbWm20da04HVDRoUf2LBXcfcysqF29/i4oRBZTZo4zbzKx3OZIzooM7pSjT9STBav2H9Iu0GIf2oEk8cA=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqKK0NZ8kRrXg1mO/rikxwwyNU9kmY0+ZiXTN2Hh5Tqi9sOZqFI9osLE21+i5YqTTaud94fbdAS/viU+3HdVMbOkX9ZvqsELa4k19fKPxxXlg3VzJoNKqXnxoVEJ2EcTd2VK1TBUosi4hXt+Q1F91bwd6nbzs6WP/84ieFwOIP3sr2bczOnXwQIHmGft4Xw25XjgGh4R0uAyFCRzMcZ99om++BPcNOV8PFqM6w7M9cAf11Q/qgZQuCdGTM5qStcdT4Dthzvgs6lD1aFXqVIav26Y6ALRxsHVgWN10P7+5uy1p16L+YRFhwx9QiXYModqUmDQ94g7cmpnaT/f6RaJuTQIDAQAB
  notifyUrl: http://xxx/api/system/amount/order/notify
