server:
  port: 8000
  servlet:
    context-path: /api/system


spring:
  application:
    name: management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/managerment
    username: root
    password: a123456
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
      timeout: 5000
      password: 123456
    # springAI
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-7a1fd5298eff41f590350ade6e642165
      chat:
        options:
          model: qwen-plus

mybatis-plus:
  configuration:
    # 驼峰配置
    map-underscore-to-camel-case: false
    # 开发环境打印 Sql 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Knife4j配置
# springdoc-openapi配置
springdoc:
  # get请求多参数时不需要添加额外的@ParameterObject和@Parameter注解
  default-flat-param-object: true
  # 启用swaggerUI
  swagger-ui:
    #自定义swagger前端请求路径，输入http://127.0.0.1:8080/api/system/swagger-ui.html会自动重定向到swagger页面
    path: /swagger-ui.html
    enabled: true
    operations-sorter: order
  api-docs:
    path: /v3/api-docs
    enabled: true
# knife4j相关配置 可以不用改
knife4j:
  enable: true
  setting:
    language: ZH_CN   # 中文:ZH_CN 英文:EN
    enable-swagger-models: true
    enable-dynamic-parameter: false
    enable-footer-custom: true
    enable-footer: true
    enable-document-manage: true

store:
  init:
    storeName: "qzh的便利店"
    managerId: 1991058483334778881
    contactName: "qzh"
    contactPhone: "13800138000"
    contactEmail: "qzh@example.com"
    address: "北京市朝阳区建国路88号"
    longitude: 116.481028
    latitude: 39.921983

baidu:
  weather:
    base-url: https://api.map.baidu.com/weather/v1/
    ak: jwE991y5wmyqLVa90OssRsYoqw9WfvRF
    connect-timeout-ms: 5000
    read-timeout-ms: 5000

alipay:
  appId: 9021000161645557
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC/0LN33ZxOBGx11y/O4kVkc7+lThx9+r/bbgAIK/eh/3UJ8NL3iVsy1LKTAC9JvRCKI1XOYFMmiCoXxaRXSlgxxkgUzk/LSNdjtGKGFDX849R31z8hsDDsNOxgzOeB5dotiNJcJ4LFBy3hSFjbI/eInsy4GdZ+Q7ZlQ55+50YRufRUtikftd5qDiqHiy3Qmm7qfuYZXQR6BoPaFbYOXdiY+LpWuFKMmmZAZzprvrPs00PSOWPWVK7fcVHW1/6SixEGXdVAI5kI7phWeM7TcUVDQ5CT/QyEzptI87CZACdCbMSrZ2coZNehSTl9j9cUW36TtoWgyejsJYWHwUuSU74nAgMBAAECggEBAJQZpsgQ4oNWZQvjVvVsvVlfCYSvt84JUiMxXnLwx6Vb4VkIiUs40aKAmVRo2xobEW8m8zSCKRFiJuXt4wLG0yuzRapS1UdG+Y7xEvUlG74jhsP0/LidGlj2T+A5tTIVb4yizJD8rLpF3cXIn1qr/Y6N1dD7miIpU+YB/JlNJku+KsPVneMHCsQU/n50YSP5SY7hkqphLVdwLSoipOxwneUOJvnCtOShzN1gNXFDSyXOB577j309UHeSFCw/iqSweJtMDH1tgVspyhxGUbr+vUJuPJaPkdFUzgusMQxRURuwft4AeEOMx2N4pelmx20yKiiRX8Hw/9DJVix5dgDFKRECgYEA4mazedg4rpAibi0OQGKx00x1z9oZh4EJxLboThTE2rH5ZH7P78DzW3nKASMhyZ4DevmI4+BmoBatoTEPYo2OC/26LFufSyX31D0D4jabHUO1+pHwcC8adFX9hxvB1j75MBby7znRStHqRuNJEsuWu67niTehNtkDukIVOUh+7TkCgYEA2OR2POsIXw2H5RKWYyjwibooqyy49XlsGz+caNWqHtq/tffp7kP4wCMBMwXmFZA8dsGIWlD1/Kr5IGDMSHDGFy6mlcQ5WnxShzeC3guvoRWB53omBrCF61wKKuILwLXQr9di5YYjqpjnSnXTmF2VjBLiiwxGA8wBDRkknUNdZl8CgYATcvssFnUYGe27RUeaJGBeZI0iY/wZde5e5c+jFYmrt+pSxcobMJo3W4kM+/WlGlv2LoWh/d8TFZ+o30wRDVQMl6lsshpHHGXj57HztvkwVGbHtc3P9VvyboivGKVYQGSryuznvDHMmafkmxXl9XNngCkH0q2Yxp/ZWl/0YdP1kQKBgBqq7IbM9ziIt17JDEig7gJhK0LwusUj6tDm31pcexBUISJEmzS6ksk9BJa7cPDRzT1kylkgfz5T31HF1RhLFXAgQkdD2zFu+864WpTmpu+Nb22ArVBBQBYSOQXQyVUmhcQ5HWXPOm9tYXLcTen8B7kzUTt7hNhOqwprPv8/GyrNAoGAGIkUjNuOpTtTIcwuVt7AWCYB7sQ3HgC8y8p4yZ6Uznl/8nnXP46SjCM9yPG1HXu9QCNqZ3VlxPpc1qtABip+D5zxqhIf9NJeQYgZvU2WbajZSOW3HdPNZv6+OLhKXVexqbWVg+GFKlZeMWS8zwn8MIP9vGMqgtE2Y5ON3jmIOS8=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2YBpMADhb26wgfqmaoeSUMJglkn916/+wZZ0HdOiWfPhdA5p99ymeoJpHYqhmnYexOdx9fu2MW1UwRNxX1BPzQEqm5xjHT5ueD5hEy0hvcQNUnszh8+ltQr9wB3bbSlR3QoNKxD6pOpshrlCdIGTQmrV8r/y/QveHKX32JzuuF5DNnw6w1uIRWDJpY8eJn/Md8qBHG/qntolf1NxIikXWSpklC57bxXHwwV74f+5a3XVNLU748txUPXl9ehfwzOkJipBEfMagLaJbKDflnJUFYJzNV9jgC4Ot6GuFJsR745zSStn00wyIYcfI5JyKIK5K+nCATy2LjwD6dSnrKPODQIDAQAB
  notifyUrl: http://xxx/api/system/amount/order/notify
